.TH ENCUENTRO 1
.SH NAME
encuentro \- busque, descargue, y vea el maravilloso contenido ofrecido 
por el Canal Encuentro, Paka Paka, BACUA, Educ.ar y otros.

Note: This program is strongly oriented to Spanish speaking people, as 
the content of Canal Encuentro and the other channels is only in Spanish.


.SH SYNOPSYS
.B encuentro [-v]

.SH DESCRIPTION

Este es un simple programa que permite buscar, descargar y ver contenido de Encuentro y otros canales. Notar que este programa no distribuye contenido directamente, sino que permite un mejor uso personal de esos contenidos.

Por favor, referirse a los sitios web correspondientes para saber qué se puede y qué no se puede hacer con los contenidos de tales sitios.

Si se ejecuta con 
.B -v 
mostrará las lineas de log en stdout.

.SH AUTHOR
Facundo Batista <facundo@taniquetil.com.ar>

.SH SEE ALSO
La página del proyecto es http://encuentro.taniquetil.com.ar/

El desarrollo está centralizado en https://launchpad.net/launcherposta


