#!/bin/bash
#
# Copyright 2014-2020 Facundo Batista

set -eu

PYTHONPATH=server fades -r requirements.txt -x nosetests -v -s tests
fades -d flake8 -x flake8 --max-line-length=99 server encuentro
pylint -d R,C,W,E -e C0111,C0112  -r n -f colorized --no-docstring-rgx="(__.*__|test_*)" encuentro server 2> /dev/null
