#!/bin/bash
#
# Copyright 2014-2015 Facundo Batista

set -eu

fades -r requirements_py2.txt --python=python2 -x nosetests -v -s tests --exclude=test_dqsv_scrapers.py --exclude=test_ted1_scrapers.py --exclude=test_cda_scrapers.py
fades -r requirements_py3.txt -x nosetests -v -s tests/test_dqsv_scrapers.py tests/test_ted1_scrapers.py tests/test_cda_scrapers.py
flake8 --max-line-length=99 encuentro server
pylint -d R,C,W,E -e C0111,C0112  -r n -f colorized --no-docstring-rgx="(__.*__|test_*)" encuentro server 2> /dev/null
