name: encuentro
base: core20 
version: '6.0'
summary: Search, download and see the wonderful content from Encuentro and others.
description: |
    Simple application that allows one to search, download and see the 
    wonderful content from Encuentro Encuentro, Paka Paka, BACUA, Educ.ar, 
    TEDx and other channels.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
    encuentro:
        command: bin/encuentro
        plugs:
            - home            # so it can acess files under the user's home
            - removable-media # so it can access things in /media, etc. (manually connected)
            - network         # to get the content
            - desktop         # so the right default media player can be used
        extensions:
            - kde-neon

parts:
    encuentro:
        plugin: python
        source: .
        requirements: 
            - requirements.txt
        stage-packages:
            - libgtk-3-0
            - libqt53danimation5
            - libqt53dextras5
            - libqt53dquick5
            - libqt53dquickscene2d5
            - libqt5gamepad5
            - libspeechd2
            - libatk-bridge2.0-0
            - libatspi2.0-0
            - libxinerama1
        organize:
            lib/python3.8/site-packages: lib/
        stage:
            - bin/encuentro
            - lib/certifi
            - lib/certifi-*.dist-info
            - lib/chardet
            - lib/chardet-*.dist-info
            - lib/defer
            - lib/defer-*.dist-info
            - lib/encuentro
            - lib/encuentro-*.dist-info
            - lib/idna
            - lib/idna-*.dist-info
            - lib/pkg_resources
            - lib/pkg_resources-*.dist-info
            - lib/PyQt5
            - lib/PyQt5-*.dist-info
            - lib/PyQt5_Qt5-*.dist-info
            - lib/PyQt5_sip-*.dist-info
            - lib/requests
            - lib/requests-*.dist-info
            - lib/setuptools
            - lib/setuptools-*.dist-info
            - lib/urllib3
            - lib/urllib3-*.dist-info
            - lib/xdg
            - lib/pyxdg-*.dist-info
            - lib/youtube_dl
            - lib/youtube_dl-*.dist-info
            - "**/libQt53DAnimation.so.*"
            - "**/libQt53DCore.so.*"
            - "**/libQt53DExtras.so.*"
            - "**/libQt53DInput.so.*"
            - "**/libQt53DLogic.so.*"
            - "**/libQt53DQuick.so.*"
            - "**/libQt53DQuickScene2D.so.*"
            - "**/libQt53DRender.so.*"
            - "**/libQt5Gamepad.so.*"
            - "**/libatk-1.0.so.*"
            - "**/libgdk-3.so.*"
            - "**/libgtk-3.so.*"
            - "**/libspeechd.so.*"
